name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*'          # déclenche Docker build sur tag release
  pull_request:
    branches:
      - main
  workflow_dispatch:   # déclenche manuel

jobs:
  lint:
    if: >
      github.ref_type != 'tag' && 
      github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

  testing:
    if: >
      github.ref_type != 'tag' && 
      github.event_name != 'workflow_dispatch'
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test

      - name: Run Integration Test
        run: echo "Hello Integration !"

  build-image:
    if: >
      startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.16-dind
        options: --privileged
    env:
      IMAGE_TAG: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build --platform=linux/amd64 -t $IMAGE_TAG -t ghcr.io/${{ github.repository }}:latest .
          docker push ghcr.io/${{ github.repository }} --all-tags

  release:
    if: >
      github.ref == 'refs/heads/main' &&
      github.ref_type != 'tag' &&
      !startsWith(github.event.head_commit.message, 'chore: release')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Release with release-it
        run: npx --yes release-it --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}