name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*'          # dÃ©clenche Docker build sur tag release
  pull_request:
    branches:
      - main
  workflow_dispatch:   # dÃ©clenche manuel

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“¥ Checkout repository
        uses: actions/checkout@v4

      - name: ðŸ”§ Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: package-lock.json
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: ðŸ“¦ Install dependencies
        working-directory: ./src
        run: npm ci

      - name: Run Lint
        run: npm run lint

  testing:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“¥ Checkout repository
        uses: actions/checkout@v4

      - name: ðŸ”§ Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: package-lock.json
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: ðŸ“¦ Install dependencies
        working-directory: ./src
        run: npm ci

      - name: Run Unit Tests
        run: npm run test

      - name: Run Integration Test
        run: echo "Hello Integration !"

  build-image:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.16-dind
        options: --privileged
    env:
      IMAGE_TAG: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
    steps:
      - name: ðŸ“¥ Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build --platform=linux/amd64 -t $IMAGE_TAG -t ghcr.io/${{ github.repository }}:latest .
          docker push ghcr.io/${{ github.repository }} --all-tags

  release:
    if: github.ref_name == 'main'
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“¥ Checkout repository
        uses: actions/checkout@v4

      - name: ðŸ”§ Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: package-lock.json
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Release with release-it
        run: npx --yes release-it --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
